export const REQ_ACTIVATIONS = "REQ_ACTIVATIONS";
export const SET_ACTIVATIONS = "SET_ACTIVATIONS";
export const FAIL_ACTIVATIONS = "FAIL_ACTIVATIONS";
export const SET_SELECTED_ACTIVATION = "SET_SELECTED_ACTIVATION";
