export const REQ_ACTIVATION_TYPES = "REQ_ACTIVATION_TYPES";
export const SET_ACTIVATION_TYPES = "SET_ACTIVATION_TYPES";
export const FAIL_ACTIVATION_TYPES = "FAIL_ACTIVATION_TYPES";
export const SET_SELECTED_ACTIVATION_TYPE = "SET_SELECTED_ACTIVATION_TYPE";
