export const REQ_LOCATIONS = "REQ_LOCATIONS";
export const SET_LOCATIONS = "SET_LOCATIONS";
export const FAIL_LOCATIONS = "FAIL_LOCATIONS";
export const SET_SELECTED_LOCATION = "SET_SELECTED_LOCATION";
export const SET_NEW_LOCATION = "SET_NEW_LOCATION";
export const GET_SYNC_DATA = "GET_SYNC_DATA";
export const GET_SYNC_DATA_FAIL = "GET_SYNC_DATA_FAIL";
